version: '3.8'

services:
  mariadb-culture:
    image: mariadb:11.7.2-ubi9
    container_name: mariadb-culture
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    volumes:
      - ./mariadb_data/:/var/lib/mysql:Z
      - ./mariadb_init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10


  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    restart: unless-stopped


  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8003:8003"
    environment:
      - MYSQL_HOST=mariadb-culture
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=Culture
      - MYSQL_POOL_SIZE=10
      - MYSQL_POOL_NAME=CultureAppMariaDBPool
      - JWT_SECRET_KEY=d8a3f7c9e1b2a4d6f8e0c2b1a3d5e7f9c1b2a4d6f8e0c2b1a3d5e7f9c1b2a4d6
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - OLLAMA_URL=http://ollama:11434/api
      - MODEL_NAME=gemma3:1b
    depends_on:
      ollama:
        condition: service_started
      mariadb-culture:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 10s
      timeout: 5s
      retries: 10


  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - BACKEND_API_URL=http://backend:8003
    depends_on:
      backend:
        condition: service_healthy
    restart: always
